apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      httpMethod: "POST"

  - name: Elasticsearch-Logs
    type: elasticsearch
    access: proxy
    url: http://elasticsearch-monitoring:9200
    database: "logs-*"
    timeField: "@timestamp"
    editable: true
    jsonData:
      interval: "Daily"
      timeField: "@timestamp"
      esVersion: "8.0.0"
      maxConcurrentShardRequests: 5
      logMessageField: "message"
      logLevelField: "level"

  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    editable: true
    jsonData:
      tracesToLogs:
        datasourceUid: "elasticsearch-logs"
        tags: ["job", "instance", "pod", "namespace"]
        mappedTags: [{"key": "service.name", "value": "service"}]
        mapTagNamesEnabled: false
        spanStartTimeShift: "1h"
        spanEndTimeShift: "1h"
        filterByTraceID: false
        filterBySpanID: false

  - name: Elasticsearch-APM
    type: elasticsearch
    access: proxy
    url: http://elasticsearch-monitoring:9200
    database: "apm-*"
    timeField: "@timestamp"
    editable: true
    jsonData:
      interval: "Daily"
      timeField: "@timestamp"
      esVersion: "8.0.0"

  - name: Vector-Metrics
    type: prometheus
    access: proxy
    url: http://vector-monitoring:9598
    editable: true
    jsonData:
      timeInterval: "30s"
