global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@nexus-v3.local'
  smtp_auth_username: 'alerts@nexus-v3.local'
  smtp_auth_password: 'password'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 5s
      repeat_interval: 30m
    
    - match:
        category: infrastructure
      receiver: 'infrastructure-alerts'
      group_interval: 5m
    
    - match:
        category: application
      receiver: 'application-alerts'
      group_interval: 2m
    
    - match:
        category: monitoring
      receiver: 'monitoring-alerts'
      group_interval: 10m

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://localhost:5001/webhook'
        send_resolved: true
        http_config:
          basic_auth:
            username: 'webhook_user'
            password: 'webhook_password'

  - name: 'critical-alerts'
    email_configs:
      - to: 'oncall@nexus-v3.local'
        subject: '[CRITICAL] {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Labels: {{ range .Labels.SortedPairs }}{{ .Name }}={{ .Value }} {{ end }}
          {{ end }}
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#alerts-critical'
        title: 'Critical Alert'
        text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        send_resolved: true

  - name: 'infrastructure-alerts'
    email_configs:
      - to: 'infrastructure@nexus-v3.local'
        subject: '[INFRA] {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        body: |
          Infrastructure Alert Details:
          {{ range .Alerts }}
          - Alert: {{ .Annotations.summary }}
          - Description: {{ .Annotations.description }}
          - Instance: {{ .Labels.instance }}
          - Time: {{ .StartsAt }}
          {{ end }}

  - name: 'application-alerts'
    email_configs:
      - to: 'developers@nexus-v3.local'
        subject: '[APP] {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        body: |
          Application Alert Details:
          {{ range .Alerts }}
          - Service: {{ .Labels.service }}
          - Alert: {{ .Annotations.summary }}
          - Description: {{ .Annotations.description }}
          - Time: {{ .StartsAt }}
          {{ end }}

  - name: 'monitoring-alerts'
    email_configs:
      - to: 'monitoring@nexus-v3.local'
        subject: '[MONITORING] {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        body: |
          Monitoring System Alert:
          {{ range .Alerts }}
          - Component: {{ .Labels.job }}
          - Alert: {{ .Annotations.summary }}
          - Description: {{ .Annotations.description }}
          {{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']

  - source_match:
      alertname: 'ServiceDown'
    target_match_re:
      alertname: '(HighErrorRate|HighResponseTime)'
    equal: ['service']
