packages:
    - "apps/*"
    - "packages/*"
    - "scripts/*"
    - "tools/*"

catalog:
  # Shared dependencies
  typescript: ^5.0.0
  '@types/node': ^20.0.0
  eslint: ^8.0.0
  prettier: ^3.0.0

  # React ecosystem
  react: ^18.2.0
  react-dom: ^18.2.0
  '@types/react': ^18.0.0

  # Build tools
  vite: ^4.0.0
  rollup: ^3.0.0

catalogs:
  frontend:
    react: ^18.2.0
    react-dom: ^18.2.0
    next: ^13.0.0

  backend:
    express: ^4.18.0
    fastify: ^4.0.0
    '@types/express': ^4.17.0
