apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-web
  labels:
    app: nexus-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nexus-web
  template:
    metadata:
      labels:
        app: nexus-web
    spec:
      containers:
      - name: web
        image: nexus-web:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: API_URL
          value: "http://nexus-api-service:3001"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
